apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: filesystem 
  namespace: toolhive-system
spec:
  image: mcp/filesystem:1.0.2 
  transport: stdio #streamable-http
  proxyPort: 8080
  mcpPort: 8080
  args:
    - '/projects'
  podTemplateSpec:
    spec:
      volumes:
        - name: my-mcp-data
          hostPath:
            path: /home/lab/k8s-guard-demo/data/filesystem
            type: Directory
      containers:
        - name: mcp
          args:
            - "/projects"
          volumeMounts:
            - mountPath: /projects
              name: my-mcp-data
              readOnly: true
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
